### ISSUE TITLE
Define user role

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#532]
We want to define user roles when they register and as part of the account settings

### Why
We want to know the user roles to offer a more optimized experience (Later on)

### Level
Medium

### Current behavior
We create a user, and this user is generic

### Expected behavior
The user should have multiple roles 

### Screenshot attached
![role-page-config](https://user-images.githubusercontent.com/88840/77307081-ebae9d80-6cf8-11ea-87f0-a204004a867f.png)
![role-page](https://user-images.githubusercontent.com/88840/77307087-eea98e00-6cf8-11ea-9cc8-0e02ab1c12b6.png)

### Assets
![icon-maintain](https://user-images.githubusercontent.com/88840/77308134-c6229380-6cfa-11ea-8714-1e5915576369.png)
![icon-contribution](https://user-images.githubusercontent.com/88840/77308135-c753c080-6cfa-11ea-83a6-6934d1907c15.png)
![icon-funding](https://user-images.githubusercontent.com/88840/77308138-c753c080-6cfa-11ea-9f9f-e9be8ce47ef4.png)

### How to reproduce the user scenario
 - Create a user
 - A screen will ask to define user roles
 - We should record the current user role
 - We should have a page in preferences to change user roles

### Tips
Create table `roles` and a user can have multiple roles

**Comment by gnyani** [comment]
Hi @alexanmtz,

I tried reaching you over email and I was not able to get to you.
The issue seems interesting to me but I have spare time only during weekends.  Would that be ok for you? I can work on this issue on Saturday and Sunday. 
I am happy to take up this task. BTW, I have already registered on Gitpay long ago. 
Just one question, how does communication happen? If I have a question regarding mockup or anything else, is there someone I could reach out to, or should I just need to comment on git? 
Keep me posted.

**Comment by alexanmtz** [comment]
@gnyani, you can comment here or reach out on Slack. And that's fine that you will work on the weekend

**Comment by gnyani** [comment]
Cool, thanks.

**Comment by alexanmtz** [comment]
Hey @gnyani, you're now assigned and you can start to work on this issue 👍

**Comment by alexanmtz** [comment]
@gnyani no response from so I will unassign you from this issue

**Comment by namandangi** [comment]
I'll work on this @alexanmtz

**Comment by alexanmtz** [comment]
@namandangi you're now assigned to this issue 👍
