### ISSUE TITLE
Apply to solve - change input to textarea

### ISSUE THREAD

**Issue by vczb** [worknenjoy/gitpay#888]
Description 

### Why
I can't  write a good explanation to this `Tell about your interest in solve this task and any plan in mind` question only with 120 characters, i suggest change it to text area and add more characters.

### Level
Ease

### Current behavior
Write all in only 120

### Expected behavior
have more comfortable space and chars to say what is in or mind

### Screenshot attached

**before:**
![image](https://user-images.githubusercontent.com/51221635/160246968-e2ac6a1b-04ab-4a84-807f-3e8d9580086b.png)

**after: (example)**
![image](https://user-images.githubusercontent.com/51221635/160247019-d54f3ce2-03d9-494b-a66a-042c2329fa8c.png)

**Comment by alexanmtz** [comment]
Hello, @vczb very good suggestion for improvement, do you have the interest to work on this issue? I could add on Gitpay and we would offer a bounty to implement your solution.

**Comment by vczb** [comment]
Great, i like to work on it

**Comment by GitpayPop** [comment]
This issue was added to Gitpay, check the task [https://gitpay.me/#/task/617](https://gitpay.me/#/task/617) 💝

[About Gitpay platform](https://gitpay.me).

For portuguese, you can [access the portuguese version](https://github.com/worknenjoy/gitpay-github-app/blob/master/first-comment.pt-br.md)

### 📋 Step by Step

#### If you are the task owner who created this issue
- [x] 🔔 ***Issue open*** an issue was created
- [x] 👌 **Issue added on Gitpay** this issue was added on gitpay [https://gitpay.me/#/task/617](https://gitpay.me/#/task/617)
- [ ] 📝 **Add bounties** A bounty is added to get things done
- [ ] 📝 **Set a deadline** A deadline to finish the task (optional)
- [ ] 💾 **Choose a contributor interested** You can choose someone interested that will be able to solve your issue

#### If you want to contribute and be rewarded
- [ ] 💾 **A contributor is interested** You can show interest on the task page clicking in "I'm interested"
- [ ] 💾 **You can offer** You can make an offer
- [ ] 🔀 **You can be assigned**. You can be assigned, you should work on the task and send a Pull Request.
- [ ] 💬 **Review** Ask in comments for a review :)
- [ ] 🏁 **Approved** Once approved you will receive your payment

### 📋 Task status
- [x] ***OPEN***
- [ ] ***IN PROGRESS***
- [ ] ***DONE***

### Good to know

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. For a more compreenhensive guide to create the Pull Request properly, you can access: https://guides.github.com/activities/hello-world/

3. You can [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/)

### 🤔❓ Questions
Leave a comment below!
This issue was a comment made by our GitpayBot [Gitpay Bot](https://github.com/gitpaybot).

**Comment by alexanmtz** [comment]
Hey @vczb , this issue was imported to Gitpay https://gitpay.me/#/task/617

So just send an offer or I can suggest, maybe $20?

**Comment by vczb** [comment]
> Hey @vczb , this issue was imported to Gitpay https://gitpay.me/#/task/617
> 
> So just send an offer or I can suggest, maybe $20?

USD$ 20 it's fine, i will propose it offer

**Comment by vczb** [comment]
hello @alexanmtz it's able to review in PR #893
